//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hourglass.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hourglass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string AboutDialogCloseButtonContent {
            get {
                return ResourceManager.GetString("AboutDialogCloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贡献: 的本地化字符串。
        /// </summary>
        public static string AboutDialogContributeOnGitHub {
            get {
                return ResourceManager.GetString("AboutDialogContributeOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许可证: 的本地化字符串。
        /// </summary>
        public static string AboutDialogLicense {
            get {
                return ResourceManager.GetString("AboutDialogLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页: 的本地化字符串。
        /// </summary>
        public static string AboutDialogMoreInformation {
            get {
                return ResourceManager.GetString("AboutDialogMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 沙漏 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream BeepLoud {
            get {
                return ResourceManager.GetStream("BeepLoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream BeepNormal {
            get {
                return ResourceManager.GetStream("BeepNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream BeepQuiet {
            get {
                return ResourceManager.GetStream("BeepQuiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复选项 &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string CommandLineArgumentsParseExceptionDuplicateSwitchFormatString {
            get {
                return ResourceManager.GetString("CommandLineArgumentsParseExceptionDuplicateSwitchFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效输入 &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string CommandLineArgumentsParseExceptionInvalidTimerInputFormatString {
            get {
                return ResourceManager.GetString("CommandLineArgumentsParseExceptionInvalidTimerInputFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 &quot;{0}&quot; 无效值 &quot;{1}&quot; 的本地化字符串。
        /// </summary>
        public static string CommandLineArgumentsParseExceptionInvalidValueForSwitchFormatString {
            get {
                return ResourceManager.GetString("CommandLineArgumentsParseExceptionInvalidValueForSwitchFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 &quot;{0}&quot; 缺少值 的本地化字符串。
        /// </summary>
        public static string CommandLineArgumentsParseExceptionMissingValueForSwitchFormatString {
            get {
                return ResourceManager.GetString("CommandLineArgumentsParseExceptionMissingValueForSwitchFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知选项 &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string CommandLineArgumentsParseExceptionUnrecognizedSwitchFormatString {
            get {
                return ResourceManager.GetString("CommandLineArgumentsParseExceptionUnrecognizedSwitchFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string ContextMenuAboutMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuAboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级选项 的本地化字符串。
        /// </summary>
        public static string ContextMenuAdvancedOptionsMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuAdvancedOptionsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置顶 的本地化字符串。
        /// </summary>
        public static string ContextMenuAlwaysOnTopMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuAlwaysOnTopMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序名称 的本地化字符串。
        /// </summary>
        public static string ContextMenuApplicationNameWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuApplicationNameWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string ContextMenuClearRecentInputsMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuClearRecentInputsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string ContextMenuClearSavedTimersMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuClearSavedTimersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string ContextMenuCloseMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuCloseMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束后退出 的本地化字符串。
        /// </summary>
        public static string ContextMenuCloseWhenExpiredMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuCloseWhenExpiredMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夜间 的本地化字符串。
        /// </summary>
        public static string ContextMenuDarkThemeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuDarkThemeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不保持电脑唤醒 的本地化字符串。
        /// </summary>
        public static string ContextMenuDoNotKeepComputerAwakeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuDoNotKeepComputerAwakeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏 的本地化字符串。
        /// </summary>
        public static string ContextMenuFullScreenMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuFullScreenMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白昼 的本地化字符串。
        /// </summary>
        public static string ContextMenuLightThemeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuLightThemeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环 的本地化字符串。
        /// </summary>
        public static string ContextMenuLoopSoundMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuLoopSoundMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环 的本地化字符串。
        /// </summary>
        public static string ContextMenuLoopTimerMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuLoopTimerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理... 的本地化字符串。
        /// </summary>
        public static string ContextMenuManageThemesMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuManageThemesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        public static string ContextMenuMaximizeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuMaximizeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化 的本地化字符串。
        /// </summary>
        public static string ContextMenuMinimizeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuMinimizeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建计时 的本地化字符串。
        /// </summary>
        public static string ContextMenuNewTimerMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuNewTimerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无记录 的本地化字符串。
        /// </summary>
        public static string ContextMenuNoRecentInputsMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuNoRecentInputsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无储存 的本地化字符串。
        /// </summary>
        public static string ContextMenuNoSavedTimersMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuNoSavedTimersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无声 的本地化字符串。
        /// </summary>
        public static string ContextMenuNoSoundMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuNoSoundMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题消失 的本地化字符串。
        /// </summary>
        public static string ContextMenuNoWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuNoWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部打开 的本地化字符串。
        /// </summary>
        public static string ContextMenuOpenAllSavedTimersMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuOpenAllSavedTimersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时打开储存的计时 的本地化字符串。
        /// </summary>
        public static string ContextMenuOpenSavedTimersOnStartupMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuOpenSavedTimersOnStartupMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束弹出窗口 的本地化字符串。
        /// </summary>
        public static string ContextMenuPopUpWhenExpiredMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuPopUpWhenExpiredMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 24 小时制 的本地化字符串。
        /// </summary>
        public static string ContextMenuPrefer24HourTimeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuPrefer24HourTimeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出时询问 的本地化字符串。
        /// </summary>
        public static string ContextMenuPromptOnExitMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuPromptOnExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 近期输入记录 的本地化字符串。
        /// </summary>
        public static string ContextMenuRecentInputsMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuRecentInputsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复 的本地化字符串。
        /// </summary>
        public static string ContextMenuRestoreMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuRestoreMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度条由长变短 的本地化字符串。
        /// </summary>
        public static string ContextMenuReverseProgressBarMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuReverseProgressBarMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时储存 的本地化字符串。
        /// </summary>
        public static string ContextMenuSavedTimersMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuSavedTimersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘图标 的本地化字符串。
        /// </summary>
        public static string ContextMenuShowInNotificationAreaMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuShowInNotificationAreaMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务栏进度 的本地化字符串。
        /// </summary>
        public static string ContextMenuShowProgressInTaskbarMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuShowProgressInTaskbarMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示已用时间（代替剩余时间） 的本地化字符串。
        /// </summary>
        public static string ContextMenuShowTimeElapsedMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuShowTimeElapsedMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束后关机 的本地化字符串。
        /// </summary>
        public static string ContextMenuShutDownWhenExpiredMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuShutDownWhenExpiredMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声音 的本地化字符串。
        /// </summary>
        public static string ContextMenuSoundMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuSoundMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string ContextMenuThemeMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuThemeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已用时间 · 计时标题 的本地化字符串。
        /// </summary>
        public static string ContextMenuTimeElapsedPlusTimerTitleWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimeElapsedPlusTimerTitleWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已用时间 的本地化字符串。
        /// </summary>
        public static string ContextMenuTimeElapsedWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimeElapsedWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余时间 · 计时标题 的本地化字符串。
        /// </summary>
        public static string ContextMenuTimeLeftPlusTimerTitleWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimeLeftPlusTimerTitleWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余时间 的本地化字符串。
        /// </summary>
        public static string ContextMenuTimeLeftWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimeLeftWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时标题 · 已用时间 的本地化字符串。
        /// </summary>
        public static string ContextMenuTimerTitlePlusTimeElapsedWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimerTitlePlusTimeElapsedWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时标题 · 剩余时间 的本地化字符串。
        /// </summary>
        public static string ContextMenuTimerTitlePlusTimeLeftWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimerTitlePlusTimeLeftWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时标题 的本地化字符串。
        /// </summary>
        public static string ContextMenuTimerTitleWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuTimerTitleWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未命名主题 的本地化字符串。
        /// </summary>
        public static string ContextMenuUnnamedTheme {
            get {
                return ResourceManager.GetString("ContextMenuUnnamedTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口标题 的本地化字符串。
        /// </summary>
        public static string ContextMenuWindowTitleMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuWindowTitleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-CN 的本地化字符串。
        /// </summary>
        public static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsApril {
            get {
                return ResourceManager.GetString("DateTimeExtensionsApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsAugust {
            get {
                return ResourceManager.GetString("DateTimeExtensionsAugust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsDecember {
            get {
                return ResourceManager.GetString("DateTimeExtensionsDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsFebruary {
            get {
                return ResourceManager.GetString("DateTimeExtensionsFebruary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsJanuary {
            get {
                return ResourceManager.GetString("DateTimeExtensionsJanuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsJuly {
            get {
                return ResourceManager.GetString("DateTimeExtensionsJuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsJune {
            get {
                return ResourceManager.GetString("DateTimeExtensionsJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsMarch {
            get {
                return ResourceManager.GetString("DateTimeExtensionsMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsMay {
            get {
                return ResourceManager.GetString("DateTimeExtensionsMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 日 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsNndFormatString {
            get {
                return ResourceManager.GetString("DateTimeExtensionsNndFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 11 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsNovember {
            get {
                return ResourceManager.GetString("DateTimeExtensionsNovember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 日 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsNrdFormatString {
            get {
                return ResourceManager.GetString("DateTimeExtensionsNrdFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 日 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsNstFormatString {
            get {
                return ResourceManager.GetString("DateTimeExtensionsNstFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 日 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsNthFormatString {
            get {
                return ResourceManager.GetString("DateTimeExtensionsNthFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsOctober {
            get {
                return ResourceManager.GetString("DateTimeExtensionsOctober", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 9 月 的本地化字符串。
        /// </summary>
        public static string DateTimeExtensionsSeptember {
            get {
                return ResourceManager.GetString("DateTimeExtensionsSeptember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string DateTimeTokenDateOnlyFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenDateOnlyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^({0})$ 的本地化字符串。
        /// </summary>
        public static string DateTimeTokenDateOnlyPatternFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenDateOnlyPatternFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1} 的本地化字符串。
        /// </summary>
        public static string DateTimeTokenDateTimeFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenDateTimeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^({0})\s+.*+({1})$ 的本地化字符串。
        /// </summary>
        public static string DateTimeTokenDateTimePatternFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenDateTimePatternFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^({0})\s+(,\s*)?({1})$ 的本地化字符串。
        /// </summary>
        public static string DateTimeTokenTimeDatePatternFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenTimeDatePatternFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时到{0} 的本地化字符串。
        /// </summary>
        public static string DateTimeTokenTimeOnlyFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenTimeOnlyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^({0})$ 的本地化字符串。
        /// </summary>
        public static string DateTimeTokenTimeOnlyPatternFormatString {
            get {
                return ResourceManager.GetString("DateTimeTokenTimeOnlyPatternFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下下{0} 的本地化字符串。
        /// </summary>
        public static string DayOfWeekDateTokenAfterNextFormatString {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenAfterNextFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?&lt;afternext&gt;下下个?)(?&lt;weekday&gt;(星期|周).) 的本地化字符串。
        /// </summary>
        public static string DayOfWeekDateTokenDaysOfWeekAfterNextPattern {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenDaysOfWeekAfterNextPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ((本|这)个?周?|下个?)?(?&lt;weekday&gt;(星期|周).) 的本地化字符串。
        /// </summary>
        public static string DayOfWeekDateTokenDaysOfWeekNextPattern {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenDaysOfWeekNextPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?&lt;nextweek&gt;下周)(?&lt;weekday&gt;(星期|周).) 的本地化字符串。
        /// </summary>
        public static string DayOfWeekDateTokenDaysOfWeekNextWeekPattern {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenDaysOfWeekNextWeekPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string DayOfWeekDateTokenNextFormatString {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenNextFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下周{0} 的本地化字符串。
        /// </summary>
        public static string DayOfWeekDateTokenNextWeekFormatString {
            get {
                return ResourceManager.GetString("DayOfWeekDateTokenNextWeekFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周五 的本地化字符串。
        /// </summary>
        public static string DayOfWeekExtensionsFriday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周一 的本地化字符串。
        /// </summary>
        public static string DayOfWeekExtensionsMonday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周六 的本地化字符串。
        /// </summary>
        public static string DayOfWeekExtensionsSaturday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周日 的本地化字符串。
        /// </summary>
        public static string DayOfWeekExtensionsSunday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周四 的本地化字符串。
        /// </summary>
        public static string DayOfWeekExtensionsThursday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周二 的本地化字符串。
        /// </summary>
        public static string DayOfWeekExtensionsTuesday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周三 的本地化字符串。
        /// </summary>
        public static string DayOfWeekExtensionsWednesday {
            get {
                return ResourceManager.GetString("DayOfWeekExtensionsWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string ErrorDialogCloseButtonContent {
            get {
                return ResourceManager.GetString("ErrorDialogCloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生了意外的错误 的本地化字符串。
        /// </summary>
        public static string ErrorDialogDefaultMessageText {
            get {
                return ResourceManager.GetString("ErrorDialogDefaultMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示更多信息 的本地化字符串。
        /// </summary>
        public static string ErrorDialogShowDetailsButtonContent {
            get {
                return ResourceManager.GetString("ErrorDialogShowDetailsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沙漏 的本地化字符串。
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误已记录到 &quot;{0}&quot;。 的本地化字符串。
        /// </summary>
        public static string ErrorManagerErrorHasBeenWritten {
            get {
                return ResourceManager.GetString("ErrorManagerErrorHasBeenWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法清除旧的错误记录。 的本地化字符串。
        /// </summary>
        public static string ErrorManagerFailedToClean {
            get {
                return ResourceManager.GetString("ErrorManagerFailedToClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生了意外的错误 的本地化字符串。
        /// </summary>
        public static string ErrorManagerUnexpectedError {
            get {
                return ResourceManager.GetString("ErrorManagerUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIT 许可证
        ///
        ///版权所有 © 2021 Chris Dziemborowicz
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沙漏 的本地化字符串。
        /// </summary>
        public static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} {0} 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenDayAndMonthFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenDayAndMonthFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {2} {1} {0} 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenDayMonthAndYearFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenDayMonthAndYearFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenDayOnlyFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenDayOnlyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?&lt;day&gt;\d\d?)(\s*(日|号)) 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenDayOnlyPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenDayOnlyPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} {0} 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenMonthAndDayFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenMonthAndDayFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} {0} 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenMonthAndYearFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenMonthAndYearFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {2} {1} {0} 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenMonthDayAndYearFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenMonthDayAndYearFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenMonthOnlyFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenMonthOnlyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?&lt;day&gt;\d\d?)
        ///[.\-/]
        ///(?&lt;month&gt;\d\d?)
        ///(
        ///    [.\-/]
        ///    (?&lt;year&gt;(\d\d)?\d\d)
        ///)? 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenNumericalDateWithDayFirstPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenNumericalDateWithDayFirstPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?&lt;month&gt;\d\d?)
        ///[.\-/]
        ///(?&lt;day&gt;\d\d?)
        ///(
        ///    [.\-/]
        ///    (?&lt;year&gt;(\d\d)?\d\d)
        ///)? 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenNumericalDateWithMonthFirstPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenNumericalDateWithMonthFirstPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (
        ///    (?&lt;year&gt;(\d\d)?\d\d)
        ///    [.\-/]
        ///)?
        ///(?&lt;month&gt;\d\d?)
        ///[.\-/]
        ///(?&lt;day&gt;\d\d?) 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenNumericalDateWithYearFirstPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenNumericalDateWithYearFirstPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?&lt;month&gt;\d\d?)
        ///[.\-/]
        ///(?&lt;year&gt;\d\d\d\d)
        ///|
        ///(?&lt;year&gt;\d\d\d\d)
        ///[.\-/]
        ///(?&lt;month&gt;\d\d?) 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenNumericalMonthAndYearPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenNumericalMonthAndYearPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ((?&lt;year&gt;\d\d\d\d)\s*年?\s*)?
        ///(?&lt;month&gt;\d\d?\s*月)\s*
        ///(?&lt;day&gt;\d\d?\s*)日?号? 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenSpelledDateWithDayFirstPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenSpelledDateWithDayFirstPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?&lt;month&gt;(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*)
        ///\s*(?&lt;day&gt;\d\d?)
        ///(\s*(st|nd|rd|th))?
        ///(
        ///    \s*[\s,]\s*
        ///    (?&lt;year&gt;(\d\d)?\d\d)
        ///)? 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenSpelledDateWithMonthFirstPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenSpelledDateWithMonthFirstPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ((?&lt;year&gt;\d\d\d\d)\s*年?\s*)?
        ///(?&lt;month&gt;\d\d?\s*月) 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenSpelledMonthAndOptionalYearPattern {
            get {
                return ResourceManager.GetString("NormalDateTokenSpelledMonthAndOptionalYearPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string NormalDateTokenYearOnlyFormatString {
            get {
                return ResourceManager.GetString("NormalDateTokenYearOnlyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上午  的本地化字符串。
        /// </summary>
        public static string NormalTimeTokenAmSuffix {
            get {
                return ResourceManager.GetString("NormalTimeTokenAmSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string NormalTimeTokenHourPartFormatString {
            get {
                return ResourceManager.GetString("NormalTimeTokenHourPartFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中午  的本地化字符串。
        /// </summary>
        public static string NormalTimeTokenMiddaySuffix {
            get {
                return ResourceManager.GetString("NormalTimeTokenMiddaySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晚上 的本地化字符串。
        /// </summary>
        public static string NormalTimeTokenMidnightSuffix {
            get {
                return ResourceManager.GetString("NormalTimeTokenMidnightSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?&lt;hour&gt;\d\d)
        ///(?&lt;minute&gt;\d\d)
        ///(?&lt;military&gt;|h|hrs|hours|时) 的本地化字符串。
        /// </summary>
        public static string NormalTimeTokenMilitaryTimePattern {
            get {
                return ResourceManager.GetString("NormalTimeTokenMilitaryTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 :{0:00} 的本地化字符串。
        /// </summary>
        public static string NormalTimeTokenMinutePartFormatString {
            get {
                return ResourceManager.GetString("NormalTimeTokenMinutePartFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下午  的本地化字符串。
        /// </summary>
        public static string NormalTimeTokenPmSuffix {
            get {
                return ResourceManager.GetString("NormalTimeTokenPmSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 :{0:00} 的本地化字符串。
        /// </summary>
        public static string NormalTimeTokenSecondPartFormatString {
            get {
                return ResourceManager.GetString("NormalTimeTokenSecondPartFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ((?&lt;am&gt;上午|早上|早晨|早)\s*|(?&lt;pm&gt;中午|下午|傍晚|夜晚|晚上|晚)\s*)?
        ///(?&lt;hour&gt;\d\d?)
        ///(
        ///    (?&lt;minute&gt;\d\d)
        ///    (?&lt;second&gt;\d\d)?
        ///)?
        ///\s*
        ///((?&lt;military&gt;h|hrs|hours|时)|整?点)? 的本地化字符串。
        /// </summary>
        public static string NormalTimeTokenTimeWithoutSeparatorsPattern {
            get {
                return ResourceManager.GetString("NormalTimeTokenTimeWithoutSeparatorsPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ((?&lt;am&gt;上午|中午|早上|早晨|早)\s*|(?&lt;pm&gt;下午|傍晚|夜晚|晚上|晚)\s*)?
        ///(?&lt;hour&gt;\d\d?)\s*([.:]|点?|时?)\s*
        ///(
        ///    (?&lt;minute&gt;\d\d?)\s*([.:]|分?)\s*
        ///    (
        ///    (?&lt;second&gt;\d\d?)\s*秒?\s*
        ///    )?
        ///)?
        ///\s*
        ///((?&lt;military&gt;h|hrs|hours|时)|整?点)? 的本地化字符串。
        /// </summary>
        public static string NormalTimeTokenTimeWithSeparatorsPattern {
            get {
                return ResourceManager.GetString("NormalTimeTokenTimeWithSeparatorsPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string NotificationAreaIconExitMenuItem {
            get {
                return ResourceManager.GetString("NotificationAreaIconExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建计时 的本地化字符串。
        /// </summary>
        public static string NotificationAreaIconNewTimerMenuItem {
            get {
                return ResourceManager.GetString("NotificationAreaIconNewTimerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间到 的本地化字符串。
        /// </summary>
        public static string NotificationAreaIconTimerExpired {
            get {
                return ResourceManager.GetString("NotificationAreaIconTimerExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时结束。 的本地化字符串。
        /// </summary>
        public static string NotificationAreaIconYourTimerHasExpired {
            get {
                return ResourceManager.GetString("NotificationAreaIconYourTimerHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        public static string RelativeDateTokenTodayName {
            get {
                return ResourceManager.GetString("RelativeDateTokenTodayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天? 的本地化字符串。
        /// </summary>
        public static string RelativeDateTokenTodayPattern {
            get {
                return ResourceManager.GetString("RelativeDateTokenTodayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明天 的本地化字符串。
        /// </summary>
        public static string RelativeDateTokenTomorrowName {
            get {
                return ResourceManager.GetString("RelativeDateTokenTomorrowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明天? 的本地化字符串。
        /// </summary>
        public static string RelativeDateTokenTomorrowPattern {
            get {
                return ResourceManager.GetString("RelativeDateTokenTomorrowPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 较响 的本地化字符串。
        /// </summary>
        public static string SoundManagerLoudBeep {
            get {
                return ResourceManager.GetString("SoundManagerLoudBeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般 的本地化字符串。
        /// </summary>
        public static string SoundManagerNormalBeep {
            get {
                return ResourceManager.GetString("SoundManagerNormalBeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 较轻 的本地化字符串。
        /// </summary>
        public static string SoundManagerQuietBeep {
            get {
                return ResourceManager.GetString("SoundManagerQuietBeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圣诞节 的本地化字符串。
        /// </summary>
        public static string SpecialDateTokenChristmasDayName {
            get {
                return ResourceManager.GetString("SpecialDateTokenChristmasDayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (ch?rist?|x)-?mass?(\s*day)?|圣诞节? 的本地化字符串。
        /// </summary>
        public static string SpecialDateTokenChristmasDayPattern {
            get {
                return ResourceManager.GetString("SpecialDateTokenChristmasDayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国庆节 的本地化字符串。
        /// </summary>
        public static string SpecialDateTokenCNNationalDayName {
            get {
                return ResourceManager.GetString("SpecialDateTokenCNNationalDayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国庆节? 的本地化字符串。
        /// </summary>
        public static string SpecialDateTokenCNNationalDayPattern {
            get {
                return ResourceManager.GetString("SpecialDateTokenCNNationalDayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元旦 的本地化字符串。
        /// </summary>
        public static string SpecialDateTokenNewYearName {
            get {
                return ResourceManager.GetString("SpecialDateTokenNewYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ny|new\s*year|元旦|新年 的本地化字符串。
        /// </summary>
        public static string SpecialDateTokenNewYearPattern {
            get {
                return ResourceManager.GetString("SpecialDateTokenNewYearPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元旦前日 的本地化字符串。
        /// </summary>
        public static string SpecialDateTokenNewYearsEveName {
            get {
                return ResourceManager.GetString("SpecialDateTokenNewYearsEveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nye|new\s*year(&apos;?s)?\s*eve|元旦前日|元旦前夜 的本地化字符串。
        /// </summary>
        public static string SpecialDateTokenNewYearsEvePattern {
            get {
                return ResourceManager.GetString("SpecialDateTokenNewYearsEvePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正午 的本地化字符串。
        /// </summary>
        public static string SpecialTimeTokenMiddayName {
            get {
                return ResourceManager.GetString("SpecialTimeTokenMiddayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (12([.:]00([.:]00)?)?\s*)?(noon|mid(-?d)?ay)|正午|中午|午时 的本地化字符串。
        /// </summary>
        public static string SpecialTimeTokenMiddayPattern {
            get {
                return ResourceManager.GetString("SpecialTimeTokenMiddayPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 午夜 的本地化字符串。
        /// </summary>
        public static string SpecialTimeTokenMidnightName {
            get {
                return ResourceManager.GetString("SpecialTimeTokenMidnightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (12([.:]00([.:]00)?)?\s*)?mid-?night|半夜|夜半|午夜|子时 的本地化字符串。
        /// </summary>
        public static string SpecialTimeTokenMidnightPattern {
            get {
                return ResourceManager.GetString("SpecialTimeTokenMidnightPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑 的本地化字符串。
        /// </summary>
        public static string ThemeManagerBlackDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerBlackDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑 的本地化字符串。
        /// </summary>
        public static string ThemeManagerBlackLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerBlackLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蓝 的本地化字符串。
        /// </summary>
        public static string ThemeManagerBlueDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerBlueDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蓝 的本地化字符串。
        /// </summary>
        public static string ThemeManagerBlueLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerBlueLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灰 的本地化字符串。
        /// </summary>
        public static string ThemeManagerGrayDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerGrayDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灰 的本地化字符串。
        /// </summary>
        public static string ThemeManagerGrayLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerGrayLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绿 的本地化字符串。
        /// </summary>
        public static string ThemeManagerGreenDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerGreenDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绿 的本地化字符串。
        /// </summary>
        public static string ThemeManagerGreenLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerGreenLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建主题 的本地化字符串。
        /// </summary>
        public static string ThemeManagerNewTheme {
            get {
                return ResourceManager.GetString("ThemeManagerNewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 橙 的本地化字符串。
        /// </summary>
        public static string ThemeManagerOrangeDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerOrangeDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 橙 的本地化字符串。
        /// </summary>
        public static string ThemeManagerOrangeLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerOrangeLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紫 的本地化字符串。
        /// </summary>
        public static string ThemeManagerPurpleDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerPurpleDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紫 的本地化字符串。
        /// </summary>
        public static string ThemeManagerPurpleLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerPurpleLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 红 的本地化字符串。
        /// </summary>
        public static string ThemeManagerRedDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerRedDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 红 的本地化字符串。
        /// </summary>
        public static string ThemeManagerRedLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerRedLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夜间 的本地化字符串。
        /// </summary>
        public static string ThemeManagerWindowDarkThemesSectionHeader {
            get {
                return ResourceManager.GetString("ThemeManagerWindowDarkThemesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除该主题吗？ 的本地化字符串。
        /// </summary>
        public static string ThemeManagerWindowDeletePrompt {
            get {
                return ResourceManager.GetString("ThemeManagerWindowDeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 白昼 的本地化字符串。
        /// </summary>
        public static string ThemeManagerWindowLightThemesSectionHeader {
            get {
                return ResourceManager.GetString("ThemeManagerWindowLightThemesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要保存当前更改吗？ 的本地化字符串。
        /// </summary>
        public static string ThemeManagerWindowSavePrompt {
            get {
                return ResourceManager.GetString("ThemeManagerWindowSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string ThemeManagerWindowUserProvidedThemesSectionHeader {
            get {
                return ResourceManager.GetString("ThemeManagerWindowUserProvidedThemesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黄 的本地化字符串。
        /// </summary>
        public static string ThemeManagerYellowDarkTheme {
            get {
                return ResourceManager.GetString("ThemeManagerYellowDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黄 的本地化字符串。
        /// </summary>
        public static string ThemeManagerYellowLightTheme {
            get {
                return ResourceManager.GetString("ThemeManagerYellowLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} (已结束) 的本地化字符串。
        /// </summary>
        public static string TimerExpiredFormatString {
            get {
                return ResourceManager.GetString("TimerExpiredFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} (已结束) 的本地化字符串。
        /// </summary>
        public static string TimerExpiredLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerExpiredLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} &quot;{2}&quot; (已结束) 的本地化字符串。
        /// </summary>
        public static string TimerExpiredWithTitleFormatString {
            get {
                return ResourceManager.GetString("TimerExpiredWithTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} &quot;{2}&quot; (已结束) 的本地化字符串。
        /// </summary>
        public static string TimerExpiredWithTitleLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerExpiredWithTitleLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ➔ {1} (暂停) 的本地化字符串。
        /// </summary>
        public static string TimerPausedFormatString {
            get {
                return ResourceManager.GetString("TimerPausedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ➔ {1} (暂停) 的本地化字符串。
        /// </summary>
        public static string TimerPausedLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerPausedLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ➔ {1} &quot;{2}&quot; (暂停) 的本地化字符串。
        /// </summary>
        public static string TimerPausedWithTitleFormatString {
            get {
                return ResourceManager.GetString("TimerPausedWithTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ➔ {1} &quot;{2}&quot; (暂停) 的本地化字符串。
        /// </summary>
        public static string TimerPausedWithTitleLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerPausedWithTitleLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ➔ {1} 的本地化字符串。
        /// </summary>
        public static string TimerRunningFormatString {
            get {
                return ResourceManager.GetString("TimerRunningFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ➔ {1} (循环) 的本地化字符串。
        /// </summary>
        public static string TimerRunningLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerRunningLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ➔ {1} &quot;{2}&quot; 的本地化字符串。
        /// </summary>
        public static string TimerRunningWithTitleFormatString {
            get {
                return ResourceManager.GetString("TimerRunningWithTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ➔ {1} &quot;{2}&quot; (循环) 的本地化字符串。
        /// </summary>
        public static string TimerRunningWithTitleLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerRunningWithTitleLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 分钟 的本地化字符串。
        /// </summary>
        public static string TimerStartDefault {
            get {
                return ResourceManager.GetString("TimerStartDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^\s*((持续)?(计时)?(计)?直?等?[到至]|(un)?till?|@)\s* 的本地化字符串。
        /// </summary>
        public static string TimerStartTokenUseDateTimeParserPattern {
            get {
                return ResourceManager.GetString("TimerStartTokenUseDateTimeParserPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 秒 的本地化字符串。
        /// </summary>
        public static string TimerStartZero {
            get {
                return ResourceManager.GetString("TimerStartZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 的本地化字符串。
        /// </summary>
        public static string TimerStoppedFormatString {
            get {
                return ResourceManager.GetString("TimerStoppedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 的本地化字符串。
        /// </summary>
        public static string TimerStoppedLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerStoppedLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 &quot;{2}&quot; 的本地化字符串。
        /// </summary>
        public static string TimerStoppedWithTitleFormatString {
            get {
                return ResourceManager.GetString("TimerStoppedWithTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 &quot;{2}&quot; 的本地化字符串。
        /// </summary>
        public static string TimerStoppedWithTitleLoopedFormatString {
            get {
                return ResourceManager.GetString("TimerStoppedWithTitleLoopedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时 {0} 的本地化字符串。
        /// </summary>
        public static string TimerTimeExpiredFormatString {
            get {
                return ResourceManager.GetString("TimerTimeExpiredFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间到 的本地化字符串。
        /// </summary>
        public static string TimerTimerExpired {
            get {
                return ResourceManager.GetString("TimerTimerExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间没到 的本地化字符串。
        /// </summary>
        public static string TimerTimerNotExpired {
            get {
                return ResourceManager.GetString("TimerTimerNotExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 的本地化字符串。
        /// </summary>
        public static string TimerTimerStopped {
            get {
                return ResourceManager.GetString("TimerTimerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 — 的本地化字符串。
        /// </summary>
        public static string TimerWindowBlankTitlePlaceholder {
            get {
                return ResourceManager.GetString("TimerWindowBlankTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string TimerWindowCancelButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowCancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string TimerWindowCloseButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowCloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定退出吗？ 的本地化字符串。
        /// </summary>
        public static string TimerWindowCloseMessageBoxText {
            get {
                return ResourceManager.GetString("TimerWindowCloseMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请访问 {0} 以更新沙漏。 的本地化字符串。
        /// </summary>
        public static string TimerWindowCouldNotLaunchWebBrowserErrorMessage {
            get {
                return ResourceManager.GetString("TimerWindowCouldNotLaunchWebBrowserErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法启动浏览器 的本地化字符串。
        /// </summary>
        public static string TimerWindowCouldNotLaunchWebBrowserErrorTitle {
            get {
                return ResourceManager.GetString("TimerWindowCouldNotLaunchWebBrowserErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时: {0} &quot;{1}&quot; 的本地化字符串。
        /// </summary>
        public static string TimerWindowNewTimerWithTitleFormatString {
            get {
                return ResourceManager.GetString("TimerWindowNewTimerWithTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        public static string TimerWindowPauseButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowPauseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string TimerWindowResetButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowResetButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复 的本地化字符串。
        /// </summary>
        public static string TimerWindowResumeButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowResumeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string TimerWindowStartButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowStartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 储存 的本地化字符串。
        /// </summary>
        public static string TimerWindowStopButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowStopButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入时间或日期 的本地化字符串。
        /// </summary>
        public static string TimerWindowTimerTextHint {
            get {
                return ResourceManager.GetString("TimerWindowTimerTextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沙漏 的本地化字符串。
        /// </summary>
        public static string TimerWindowTitle {
            get {
                return ResourceManager.GetString("TimerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  ·  的本地化字符串。
        /// </summary>
        public static string TimerWindowTitleSeparator {
            get {
                return ResourceManager.GetString("TimerWindowTitleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string TimerWindowTitleTextHint {
            get {
                return ResourceManager.GetString("TimerWindowTitleTextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string TimerWindowUpdateButtonContent {
            get {
                return ResourceManager.GetString("TimerWindowUpdateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时: {0} 的本地化字符串。
        /// </summary>
        public static string TimerWindwoNewTimerFormatString {
            get {
                return ResourceManager.GetString("TimerWindwoNewTimerFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 天 的本地化字符串。
        /// </summary>
        public static string TimeSpanExtensions1DayFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensions1DayFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小时 的本地化字符串。
        /// </summary>
        public static string TimeSpanExtensions1HourFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensions1HourFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 分钟 的本地化字符串。
        /// </summary>
        public static string TimeSpanExtensions1MinuteFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensions1MinuteFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒 的本地化字符串。
        /// </summary>
        public static string TimeSpanExtensions1SecondFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensions1SecondFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 天 的本地化字符串。
        /// </summary>
        public static string TimeSpanExtensionsNDaysFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensionsNDaysFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小时 的本地化字符串。
        /// </summary>
        public static string TimeSpanExtensionsNHoursFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensionsNHoursFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 分钟 的本地化字符串。
        /// </summary>
        public static string TimeSpanExtensionsNMinutesFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensionsNMinutesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒 的本地化字符串。
        /// </summary>
        public static string TimeSpanExtensionsNSecondsFormatString {
            get {
                return ResourceManager.GetString("TimeSpanExtensionsNSecondsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   的本地化字符串。
        /// </summary>
        public static string TimeSpanExtensionsUnitSeparator {
            get {
                return ResourceManager.GetString("TimeSpanExtensionsUnitSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 天 的本地化字符串。
        /// </summary>
        public static string TimeSpanToken1DayFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1DayFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小时 的本地化字符串。
        /// </summary>
        public static string TimeSpanToken1HourFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1HourFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 分钟 的本地化字符串。
        /// </summary>
        public static string TimeSpanToken1MinuteFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1MinuteFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 个月 的本地化字符串。
        /// </summary>
        public static string TimeSpanToken1MonthFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1MonthFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒 的本地化字符串。
        /// </summary>
        public static string TimeSpanToken1SecondFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1SecondFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 周 的本地化字符串。
        /// </summary>
        public static string TimeSpanToken1WeekFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1WeekFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 年 的本地化字符串。
        /// </summary>
        public static string TimeSpanToken1YearFormatString {
            get {
                return ResourceManager.GetString("TimeSpanToken1YearFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^
        ///(
        ///    \s*
        ///    (
        ///        (
        ///            (?&lt;years&gt;\d+|\d*[.,/]\d+)
        ///            \s*
        ///            (y|yrs?|years?|年)
        ///            (
        ///                \s*
        ///                (?&lt;months&gt;\d+|\d*[.,/]\d+)
        ///                (\s+|$)
        ///            )?
        ///        )
        ///        |
        ///        (
        ///            (?&lt;months&gt;\d+|\d*[.,/]\d+)
        ///            \s*
        ///            (mo|mon?s?|months?|个月)
        ///            (
        ///                \s*
        ///                (?&lt;days&gt;\d+|\d*[.,/]\d+)
        ///                (\s+|$)
        ///            )?
        ///        )
        ///        |
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TimeSpanTokenLongFormPattern {
            get {
                return ResourceManager.GetString("TimeSpanTokenLongFormPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^
        ///\s*
        ///(?&lt;minutes&gt;\d+)
        ///\s*
        ///$ 的本地化字符串。
        /// </summary>
        public static string TimeSpanTokenMinutesOnlyPattern {
            get {
                return ResourceManager.GetString("TimeSpanTokenMinutesOnlyPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 天 的本地化字符串。
        /// </summary>
        public static string TimeSpanTokenNDaysFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNDaysFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 小时 的本地化字符串。
        /// </summary>
        public static string TimeSpanTokenNHoursFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNHoursFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 分钟 的本地化字符串。
        /// </summary>
        public static string TimeSpanTokenNMinutesFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNMinutesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 个月 的本地化字符串。
        /// </summary>
        public static string TimeSpanTokenNMonthsFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNMonthsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒 的本地化字符串。
        /// </summary>
        public static string TimeSpanTokenNSecondsFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNSecondsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 周 的本地化字符串。
        /// </summary>
        public static string TimeSpanTokenNWeeksFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNWeeksFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 年 的本地化字符串。
        /// </summary>
        public static string TimeSpanTokenNYearsFormatString {
            get {
                return ResourceManager.GetString("TimeSpanTokenNYearsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^
        ///\s*
        ///(
        ///    (
        ///        (
        ///            (
        ///                (?&lt;years&gt;\d+)
        ///                \s*[.,:\s]\s*
        ///            )?
        ///            (?&lt;months&gt;\d+)
        ///            \s*[.,:\s]\s*
        ///        )?
        ///        (?&lt;days&gt;\d+)
        ///        \s*[.,:\s]\s*
        ///    )?
        ///    (?&lt;hours&gt;\d+)
        ///    \s*[.,:\s]\s*
        ///)?
        ///(?&lt;minutes&gt;\d+)
        ///\s*[.,:\s]\s*
        ///(?&lt;seconds&gt;\d+)
        ///\s*
        ///$ 的本地化字符串。
        /// </summary>
        public static string TimeSpanTokenShortFormPattern {
            get {
                return ResourceManager.GetString("TimeSpanTokenShortFormPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   的本地化字符串。
        /// </summary>
        public static string TimeSpanTokenUnitSeparator {
            get {
                return ResourceManager.GetString("TimeSpanTokenUnitSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon TrayIcon {
            get {
                object obj = ResourceManager.GetObject("TrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 使用方法: {0} [选项] [&lt;输入&gt;]
        ///一个简单的 Windows 倒数计时器。
        ///
        ///	&lt;输入&gt;
        ///	启动计时的输入。
        ///
        ///	例如:
        ///	&quot;5&quot;			倒计时 5 分钟
        ///	&quot;5:30&quot;			倒计时 5 分钟 30 秒
        ///	&quot;7:30:00&quot;		倒计时 7 小时 30 分钟
        ///	&quot;5 分钟&quot;		倒计时 5 分钟
        ///	&quot;5 分钟 30 秒&quot;		倒计时 5 分钟 30 秒
        ///	&quot;7 小时 30 分钟&quot;	倒计时 7 小时 30 分钟
        ///	&quot;21/01/01&quot;*		倒计时到 2021 年 1 月 1 日
        ///	&quot;2021/01/01&quot;*		倒计时到 2021 年 1 月 1 日
        ///	&quot;January 1, 2021&quot;*	倒计时到 2021 年 1 月 1 日
        ///	&quot;January 1&quot;*		倒计时到 1 月 1 日
        ///	&quot;下午 2 点&quot;		倒计时到下午 2 点
        ///	&quot;14:30&quot;			倒计时到下午 2 点半
        ///	&quot;中午&quot;			倒计时到中午
        ///	&quot;午夜&quot;			倒计时到午夜
        ///	&quot;周五&quot;			倒计时到周五晚上
        ///
        ///	* 年月日顺序取决于系统设置。
        ///
        ///	支持不同的叫法，比如分和分钟、周五和星期五。
        ///
        ///选项: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于沙漏 的本地化字符串。
        /// </summary>
        public static string UsageDialogAboutHourglassHyperlinkText {
            get {
                return ResourceManager.GetString("UsageDialogAboutHourglassHyperlinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string UsageDialogCloseButtonContent {
            get {
                return ResourceManager.GetString("UsageDialogCloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令行使用方法 的本地化字符串。
        /// </summary>
        public static string UsageDialogDefaultMessageText {
            get {
                return ResourceManager.GetString("UsageDialogDefaultMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沙漏 的本地化字符串。
        /// </summary>
        public static string UsageDialogTitle {
            get {
                return ResourceManager.GetString("UsageDialogTitle", resourceCulture);
            }
        }
    }
}
